"""
Generate synthetic 23andMe-style raw files for demo and tests.

Each profile encodes a known set of phenotypes so the test suite can
assert the engine's output without needing real consumer data.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from app.core.snp_catalog import ALL_SNPS


HEADER = """\
# This file was generated by Syntrx scripts/generate_sample_data.py.
# It mimics a 23andMe v5 raw-data export. Use it to test the pipeline.
# rsid	chromosome	position	genotype
"""


@dataclass(frozen=True)
class Profile:
    name: str
    description: str
    overrides: dict[str, str]


PROFILES: list[Profile] = [
    Profile(
        "average_european",
        "Reference-allele-heavy profile with a couple of common variants.",
        {
            "rs1801133": "CT",   # MTHFR het
            "rs9939609": "AT",   # FTO het
            "rs1815739": "CT",   # ACTN3 RX
            "rs4988235": "CT",   # lactase persistent
            "rs429358": "TT", "rs7412": "CC",  # APOE ε3/ε3
        },
    ),
    Profile(
        "cyp2d6_poor_metabolizer",
        "Two CYP2D6 *4 alleles → codeine non-responder.",
        {
            "rs3892097": "AA",   # *4/*4
            "rs4244285": "GG",   # CYP2C19 *1/*1
            "rs1801133": "CT",
            "rs429358": "TT", "rs7412": "CC",
            "rs4988235": "CC",   # lactase non-persistent
        },
    ),
    Profile(
        "warfarin_sensitive_pgx_storm",
        "CYP2C9 *2/*3 + VKORC1 AA + SLCO1B1 *5/*5 + DPYD het + CYP2C19 *2/*2.",
        {
            "rs1799853": "TT",   # CYP2C9 *2 hom
            "rs1057910": "CC",   # CYP2C9 *3 hom (engine picks the worst)
            "rs9923231": "TT",   # VKORC1 AA → warfarin sensitive
            "rs4149056": "CC",   # SLCO1B1 *5 hom
            "rs3918290": "CT",   # DPYD het
            "rs4244285": "AA",   # CYP2C19 *2 hom
            "rs4988235": "CC",
        },
    ),
    Profile(
        "ultrarapid_2c19_caffeine_slow",
        "CYP2C19 *17/*17 ultrarapid + CYP1A2 slow caffeine.",
        {
            "rs12248560": "TT",  # CYP2C19 *17 hom
            "rs762551":   "CC",  # CYP1A2 slow
            "rs4988235":  "TT",  # lactase persistent
            "rs1801133":  "TT",  # MTHFR hom
        },
    ),
    Profile(
        "apoe_e4_carrier_with_iron",
        "APOE ε3/ε4 + HFE C282Y/H63D compound het + Factor V Leiden het.",
        {
            "rs429358": "CT", "rs7412": "CC",   # ε3/ε4
            "rs1800562": "GA",   # C282Y het
            "rs1799945": "CG",   # H63D het
            "rs6025":    "CT",   # FVL het
            "rs601338":  "AA",   # FUT2 non-secretor
        },
    ),
    Profile(
        "asian_alcohol_flush",
        "ALDH2*2 hom + ADH1B*2 hom — classic East Asian alcohol-sensitive profile.",
        {
            "rs671":     "AA",
            "rs1229984": "AA",
            "rs1815739": "TT",   # ACTN3 XX
        },
    ),
]


# For most SNPs, "anything that isn't the risk allele" is a safe baseline.
# A few SNPs need a specific reference allele because the engine treats
# strand-flipped reports as equivalent to the risk allele (e.g. VKORC1)
# or because the risk is a deletion (where any standard base is fine).
REFERENCE_OVERRIDES: dict[str, str] = {
    "rs9923231": "GG",   # VKORC1 reference (risk T; engine also counts A for strand)
    "rs429358":  "TT",   # APOE codon 112 reference
    "rs7412":    "CC",   # APOE codon 158 reference
    "rs1800562": "GG",   # HFE C282Y reference (risk A)
    "rs1799945": "CC",   # HFE H63D reference (risk G)
}


def _baseline_alleles(rsid: str) -> str:
    """Return the reference (no-effect) allele pair for a SNP."""
    if rsid in REFERENCE_OVERRIDES:
        return REFERENCE_OVERRIDES[rsid]
    defn = next((s for s in ALL_SNPS if s.rsid == rsid), None)
    if not defn or not defn.risk_allele:
        return "AA"
    risk = defn.risk_allele
    if risk == "-":
        return "AA"  # any non-deletion base is reference
    other = next(c for c in "ACGT" if c != risk)
    return other + other


def write_profile(profile: Profile, out_dir: Path) -> Path:
    """Write one 23andMe-format file for a profile and return its path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"sample_{profile.name}.txt"
    lines = [HEADER.rstrip()]
    for snp in ALL_SNPS:
        alleles = profile.overrides.get(snp.rsid, _baseline_alleles(snp.rsid))
        # Position is just illustrative; real files have actual coordinates
        lines.append(f"{snp.rsid}\t{snp.chromosome}\t{1000 + ALL_SNPS.index(snp)}\t{alleles}")
    path.write_text("\n".join(lines) + "\n")
    return path


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "data" / "sample"
    for p in PROFILES:
        path = write_profile(p, out)
        print(f"  wrote {path.name:50s}  {p.description}")
    # Also alias the average-European profile as the canonical sample
    canon = out / "sample_23andme.txt"
    canon.write_bytes((out / "sample_average_european.txt").read_bytes())
    print(f"  alias {canon.name}")


if __name__ == "__main__":
    main()
