"""Parser format detection, allele splitting, edge cases."""

import gzip
import io
import zipfile

from app.core import parser


HEADER_23ANDME = (
    "# This data file generated by 23andMe\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)


def test_detects_23andme():
    text = HEADER_23ANDME + "rs1801133\t1\t11856378\tCT\n"
    fmt = parser.detect_format(text.splitlines())
    assert fmt == parser.FileFormat.TWENTY_THREE_AND_ME


def test_detects_ancestry():
    text = (
        "#AncestryDNA raw data download\n"
        "rsid\tchromosome\tposition\tallele1\tallele2\n"
        'rs1801133\t1\t11856378\t"C"\t"T"\n'
    )
    fmt = parser.detect_format(text.splitlines())
    assert fmt == parser.FileFormat.ANCESTRY


def test_no_call_handling():
    text = HEADER_23ANDME + "rs1801133\t1\t11856378\t--\n"
    res = parser.parse_text(text)
    g = res.genotypes["rs1801133"]
    assert g.is_no_call


def test_gzip_decompression():
    text = HEADER_23ANDME + "rs1801133\t1\t11856378\tCT\n"
    blob = gzip.compress(text.encode())
    res = parser.parse_bytes(blob)
    assert "rs1801133" in res.genotypes


def test_zip_decompression():
    text = HEADER_23ANDME + "rs1801133\t1\t11856378\tCT\n"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("genome.txt", text)
    res = parser.parse_bytes(buf.getvalue())
    assert "rs1801133" in res.genotypes


def test_only_catalog_snps_kept():
    text = HEADER_23ANDME + (
        "rs1801133\t1\t11856378\tCT\n"
        "rs99999999\t1\t12345\tAA\n"
    )
    res = parser.parse_text(text)
    assert "rs1801133" in res.genotypes
    assert "rs99999999" not in res.genotypes


def test_ancestry_split():
    text = (
        "#AncestryDNA raw data download\n"
        "rsid\tchromosome\tposition\tallele1\tallele2\n"
        'rs1801133\t1\t11856378\t"C"\t"T"\n'
    )
    res = parser.parse_text(text)
    assert res.genotypes["rs1801133"].alleles == ("C", "T")


def test_haploid_chromosome():
    # mtDNA haploid genotype is a single allele
    alleles = parser._split_genotype("A", "MT")
    assert alleles == ("A",)


def test_indel_genotype():
    assert parser._split_genotype("II", "1") == ("I", "I")
    assert parser._split_genotype("DD", "1") == ("D", "D")
