"""
Pharmacogenomic Card PDF.

A one-page summary the user can print and hand to a clinician. Built
with reportlab so we have no native deps and it works inside Docker.
"""

from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.phenotype import Phenotype
from app.core.recommendations import Finding


def _styles() -> dict[str, ParagraphStyle]:
    s = getSampleStyleSheet()
    s.add(ParagraphStyle(
        name="SyntrxTitle", parent=s["Heading1"],
        fontSize=20, textColor=colors.HexColor("#0f172a"), spaceAfter=4,
    ))
    s.add(ParagraphStyle(
        name="SyntrxSub", parent=s["Normal"],
        fontSize=10, textColor=colors.HexColor("#475569"), spaceAfter=12,
    ))
    s.add(ParagraphStyle(
        name="SyntrxBody", parent=s["Normal"],
        fontSize=10, leading=14, textColor=colors.HexColor("#1e293b"),
    ))
    s.add(ParagraphStyle(
        name="SyntrxFootnote", parent=s["Normal"],
        fontSize=8, textColor=colors.HexColor("#64748b"), leading=11,
    ))
    return {k: s[k] for k in s.byName}


def render_card(phenotypes: dict[str, Phenotype], findings: list[Finding]) -> bytes:
    """Return a PDF document as bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
        title="Syntrx Pharmacogenomic Card",
    )
    st = _styles()
    story = []

    story.append(Paragraph("Syntrx Pharmacogenomic Card", st["SyntrxTitle"]))
    story.append(Paragraph(
        f"Generated {datetime.utcnow().strftime('%Y-%m-%d')} · "
        "Show this to your prescribing clinician. Not a diagnostic document.",
        st["SyntrxSub"]))

    rows = [["Gene", "Diplotype", "Phenotype", "Activity"]]
    pgx_genes = ["CYP2D6", "CYP2C19", "CYP2C9", "VKORC1", "CYP3A5",
                 "CYP1A2", "SLCO1B1", "DPYD", "TPMT", "UGT1A1"]
    for g in pgx_genes:
        ph = phenotypes.get(g)
        if not ph:
            continue
        rows.append([
            ph.gene,
            ph.diplotype,
            ph.phenotype,
            f"{ph.activity_score:.1f}" if ph.activity_score is not None else "—",
        ])
    table = Table(rows, colWidths=[1.0 * inch, 1.6 * inch, 3.2 * inch, 0.8 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#f1f5f9")]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(table)
    story.append(Spacer(1, 14))

    # Critical alerts
    critical = [f for f in findings
                if f.requires_physician and f.confidence.value == "high"]
    if critical:
        story.append(Paragraph("<b>Clinical alerts</b>", st["SyntrxBody"]))
        story.append(Spacer(1, 4))
        for f in critical[:6]:
            story.append(Paragraph(
                f"<b>{f.title}.</b> {f.summary}",
                st["SyntrxBody"]))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 12))
    story.append(Paragraph(
        "<i>Sources: CPIC clinical guidelines, PharmGKB, FDA pharmacogenomic labels. "
        "Generated by Syntrx — not a substitute for professional medical advice.</i>",
        st["SyntrxFootnote"]))

    doc.build(story)
    return buf.getvalue()
